### ISSUE TITLE
Kazakhstan monthly deaths 2015 - 2018 

### ISSUE THREAD

**Issue by akarlinsky** [akarlinsky/world_mortality#1]
We are looking for data on monthly deaths in Kazakhstan, 2015 to 2018. 
For now, we only have 2019-2020 data. If anyone can locate such data, we would greatly appreciate it.

Potential source - The site of Kazakhstan's NSO: [https://stat.gov.kz/](https://stat.gov.kz/)

**Comment by zhibek** [comment]
@akarlinsky Thanks for your work on this.

I've also looked for monthly mortality data on stat.gov.kz but without success (I could only find yearly data).

I have seen one Kazakh media source with a reference to 2018 (combined with 2019) - possibly they saved some data that was previously released in the report that now shows 2019/2020?
https://vlast.kz/obsshestvo/40982-v-kazahstane-v-mae-nacala-rasti-izbytocnaa-smertnost.html

**Comment by dkobak** [comment]
Nice find! We can compute the 2018 values from the 2018-19 averages shown there! We could also try emailing the authors and ask if they can share the 2018 data with us directly.

**Comment by akarlinsky** [comment]
Thanks to Noah Katz, WM now has data for 2015 to 2018 from Kazakhstan's NSO. 
Some monthly values are missing, but our model can handle missing values easily.

**Comment by zhibek** [comment]
@akarlinsky That's good to hear. Out of interest, is there public access to this source data?

**Comment by akarlinsky** [comment]
Yes. it's the Monthly Socio-Economic Development bulletin: https://stat.gov.kz/edition/publication/month?lang=en.
As stated on the README :)
