### ISSUE TITLE
Argentina excess mortality

### ISSUE THREAD

**Issue by st2048** [akarlinsky/world_mortality#15]
Hello,

This [newspaper article](https://www.infobae.com/salud/2021/07/02/como-consecuencia-de-la-pandemia-la-argentina-registro-36306-muertes-en-exceso-en-2020/) has a link to the study on excess mortality in Argentina.

In the fourth paragraph, there is a hyperlink in the word ['informe'](https://drive.google.com/file/d/11z2Iytptc74LGNGyEopCCOYzOig0Kode/view) which leads to the study (opens in Google Drive).

I hope this helps.

**Comment by dkobak** [comment]
Digitized Figure 2:

```
1.0118279569892472, 26317.934782608696
2.0172043010752687, 23668.478260869564
3.0107526881720434, 25910.326086956524
3.99247311827957, 25842.391304347824
4.986021505376344, 28355.978260869564
6.015053763440861, 31548.91304347826
7.008602150537634, 34470.108695652176
7.966666666666667, 31956.521739130436
9.043010752688172, 29646.739130434784
10.024731182795698, 28084.23913043478
10.98279569892473, 25638.58695652174
11.988172043010753, 26725.54347826087
1.0118279569892472, 25570.652173913044
2.0053763440860215, 24211.95652173913
3.0107526881720434, 25638.58695652174
3.99247311827957, 24959.23913043478
4.986021505376344, 27540.76086956522
6.015053763440861, 28899.45652173913
7.008602150537634, 36032.608695652176
7.943010752688172, 37051.63043478261
9.019354838709678, 39972.82608695652
10.001075268817205, 42554.34782608695
11.018279569892472, 35421.19565217391
11.999999999999998, 31141.304347826088
```

First median 2015-2019, then 2020

**Comment by akarlinsky** [comment]
Thanks @st2048! Data and source is now up on WMD. 
I'm keeping this issue open as I hope to obtain the raw monthly numbers themselves so we can fit our model.

**Comment by akarlinsky** [comment]
Raw numbers for 2015 to 2019 added.
2020 is still digitized from plot of report, so I'm keeping this open.

**Comment by lsempe77** [comment]
I see they have daily deaths for 2020,

https://www.argentina.gob.ar/salud/coronavirus-COVID-19/sala-situacion

Look for this: Confirmados y fallecidos por fecha de reporte (acumulado)

![image](https://user-images.githubusercontent.com/9310655/126807414-9254b285-4d8a-468d-ab01-3fb0d45ec220.png)

**Comment by akarlinsky** [comment]
Thanks! but this is reported COVID deaths, same as reported to the WHO - we need all-cause mortality.
![image](https://user-images.githubusercontent.com/48435065/126811164-46360758-7da7-4e38-80ed-6bc1253d16e0.png)

**Comment by dkobak** [comment]
>  2020 is still digitized from plot of report, so I'm keeping this open.

As the NSO replied that they won't share the numbers with you as they are preliminary, should this issue be closed?
