### ISSUE TITLE
UN data update

### ISSUE THREAD

**Issue by st2048** [akarlinsky/world_mortality#16]
Hello,

I've seen the UN data has been [updated ](https://data.un.org/Data.aspx?q=deaths&d=POP&f=tableCode%3a65)a few days ago. There's now 2020 monthly data for a few more countries/territories such as American Samoa and the Isle of Man. (There's also St Helena though it may be a bit noisier). 

There's also now data on [crude death rates](https://unstats.un.org/unsd/mbs/app/DataView.aspx?tid=3&cid=762&yearfrom=2020&yearto=2021&p=Q) for Tajikistan Q1 and Q2 2021.

The [UN Population and Vital Statistics Report](https://unstats.un.org/unsd/demographic-social/products/vitstats/seratab3.pdf) also has 2020 yearly figures for some countries where monthly data has not been published (e.g. Dominican Republic, Kenya, Bangladesh, etc.). Most of these countries have 2015-19 figures in the [2019 Demographic Yearbook](https://unstats.un.org/unsd/demographic-social/products/dyb/documents/dyb2019/table18.pdf). Have you considered the possibility of having a repository with yearly data for countries where weekly/monthly/quarterly data is not available? Or perhaps adding them to Preliminary Mortality?

**Comment by dkobak** [comment]
@akarlinsky Can you respond to this? I am sure you have a better overview than I do...

**Comment by akarlinsky** [comment]
Hi, 

Sorry for the late reply.

We are thinking about this, each case has some issues and we are constantly tracking data from UNSD as well.
For AS and IM, these are very small and rates are sometimes based on less than 30 cases, and with a less certain population denominator this can lead to large errors. We have contacted AS and IM NSOs to obtain this info directly.

Tajikistan 2020Q4 disagrees with the data obtained directly from Tajikistan's NSO, so we do not know how much we can trust these quarterly rates for 2021.

Kenya has extremely low completeness of death registration (about 33% of deaths are registered) and we are currently waiting for 2021 info to understand 2020 info, which I think has even lower registration completeness.

Bangladesh it is not registered number of deaths but rather estimated number of deaths from SRS. The full report has some strange anomalies such as having the same death rate on the most old age groups, where previously it was increasing with age throughout. Generally speaking we do not provide data from SRSs but rather VS systems.

**Comment by st2048** [comment]
Good points - thanks as always for your great work!

**Comment by st2048** [comment]
Thought this may be of interest - data from Panama on 2019-2020 is now available at UN Data by month of occurrence, which  avoids the April 2020 gap in registration data. I believe you're already using the UN occurrence data for 2015-18.
