### ISSUE TITLE
Kosovo data

### ISSUE THREAD

**Issue by sondreus** [akarlinsky/world_mortality#18]
Hi - just migrating this over here

See:
https://github.com/TheEconomist/covid-19-excess-deaths-tracker/issues/19

> Hello!
> First and foremost, I want to tell you that I'm new to this, github that is.
> There are some suggestions I wanted to make regarding data on Kosovo.
> 
> The numbers on mortality which are being used are preliminary, which I suppose are from quarterly bulletins. I asked our NSO and they said so.
> For official data on mortality prior to 2020, is published on statistical yearbook, which you can download it here, page 70-71. It's in Albanian but google translate will do the trick. With these official numbers, the expected deaths will align more accurately, corresponding to seasonal trends also.
> The data for 2020 and 2021 is also preliminary. The official data on all-cause mortality is released, up until July 2021. The problem is, that monthly data for 2020 are not as of yet published, just the total number of deaths.

**Comment by akarlinsky** [comment]
Already discussed here with great help from nerdm. It's no longer relevant so I'm closing it. 

See lengthy discussion here: https://github.com/akarlinsky/world_mortality/issues/14
