### ISSUE TITLE
Colombia new source 

### ISSUE THREAD

**Issue by pr0nstar** [akarlinsky/world_mortality#23]
Hi,
Colombia just released (I think) a new mortality [dashboard](https://experience.arcgis.com/experience/d9bfa6a650a249099b5f290a6c454804/?draft=true).
According to the [manual](https://www.minsalud.gov.co/sites/rid/Lists/BibliotecaDigital/RIDE/VS/ED/GCFI/manual-usuario-tablero-exceso-mortalidad.pdf) it updates every monday and even has daily data by adm2.
![image](https://user-images.githubusercontent.com/64463227/152242673-01dc6cf1-e296-450e-abe1-01d60827b478.png)
It uses powerbi as a backend, I managed to query it with [this](https://github.com/sociedatos/sudamerica-mortalidad/blob/8bff217709e19247dcd8c225544c60e0f5d298fd/update/update.mortality.py#L347).
Greetings

**Comment by akarlinsky** [comment]
Thank you, this is very helpful! Are you going to keep the scrape updated? If so, we can switch our script to cull from you.

**Comment by pr0nstar** [comment]
Yes I will, I'll let you know if anything changes.
Data is right censored and i still dont know how long it takes to get more or less complete, avoid latest week or two:
![image](https://user-images.githubusercontent.com/64463227/152375120-ff5104c1-0b2e-49b0-be59-ffb6f11d57e9.png)
Thank you for this db.

**Comment by akarlinsky** [comment]
Good point, just updated the script to remove latest two weeks. 
How would you like to be credited as source?

**Comment by pr0nstar** [comment]
Looks like one week might be enough.
![image](https://user-images.githubusercontent.com/64463227/152820476-63b92b5c-bc42-4f25-8be9-b0056e6559da.png)
Regarding credit, please use [sociedatos](https://github.com/sociedatos).
Thank you

**Comment by akarlinsky** [comment]
One week it is then. How often do you update your scrape? I see latest is from 5 days ago.

**Comment by pr0nstar** [comment]
You are looking at the last time I edited the update script, data updates daily at 7 am GMT+0 using [github actions](https://github.com/sociedatos/sudamerica-mortalidad/actions).

**Comment by akarlinsky** [comment]
I updated the source in our README (https://github.com/akarlinsky/world_mortality#colombia-weekly)
Thanks for this great contribution!

**Comment by pr0nstar** [comment]
There was a strange update this week, maybe it would be best to wait until next tuesday to update your db
![Screenshot from 2022-03-08 21-35-59](https://user-images.githubusercontent.com/64463227/159598287-542adde4-93af-41a0-9cf7-d1415e6f217e.png)
![Screenshot from 2022-03-22 20-16-42](https://user-images.githubusercontent.com/64463227/159598410-cbeb9f0b-34e3-40ab-a66b-4ae83de03108.png)
