### ISSUE TITLE
Updated links for Brazilian mortality information

### ISSUE THREAD

**Issue by dyokomizo** [akarlinsky/world_mortality#24]
Brazilian Ministry of Health updated their site and broke a few links. The new ones are:

Sistema de Informação sobre Mortalidade – SIM (1979 a 2019):
https://opendatasus.saude.gov.br/dataset/sim-1979-2019

Sistema de Informação sobre Mortalidade – SIM (2020 a 2021): 
https://opendatasus.saude.gov.br/dataset/sim-2020-2021

**Comment by akarlinsky** [comment]
Thank you, we are already using these sources but README is indeed outdated. 
Will change it in the next WMD update.

**Comment by akarlinsky** [comment]
Readme updated in commit 67b7df1
