### ISSUE TITLE
Sweden - mortality in age group

### ISSUE THREAD

**Issue by Wolvverine** [akarlinsky/world_mortality#26]
Are here:
https://www.statistikdatabasen.scb.se/pxweb/en/ssd/START__BE__BE0101__BE0101I/Dodstal/

**Comment by akarlinsky** [comment]
Thanks, we do not collect data by age/sex/cause of death etc. since it's unavailable for most of the countries in the world.

For developed countries (like Sweden) this data exists in other datasets, I suggest using EuroStat and/or STMF.
