### ISSUE TITLE
Collect <2015 data

### ISSUE THREAD

**Issue by USMortality** [akarlinsky/world_mortality#27]
Hello, just a note, that it would be great if you could also collect <2015 data. This is especially valuable, since you seem to be fitting a slope to your baseline in your paper over 5 years - which in my experience isn't really enough datapoints to come up with a robust fit. E.g. Germany had a really low 2019 year.
Also the deaths should at least be calculated as mortality rate (deaths/100k), to de-confound against population changes.
Otherwise, thank you for doing this great work. Thanks!

P.S.: Feel free to close the comment :) Thanks!

**Comment by dkobak** [comment]
Hi, thanks for the comment.

Regarding collecting <2015 data, I guess in principle it could be good, but would require a MAJOR effort: we currently have data on 120+ countries, and for each of them we would need to look for let's say 2010--2014 data. I think it's fair to say that we are unlikely to find time to do that in any foreseeable future. @akarlinsky what do you think?

Regarding the mortality rate, the purpose of this repository is to collect raw deaths data. We compute excess deaths in another repository (https://github.com/dkobak/excess-mortality/), and there we do compute excess death rate (deaths / 100k) etc.

**Comment by akarlinsky** [comment]
Not in the foreseeable future, no. 

Closing the issue.
