### ISSUE TITLE
USA Data Missing for Week 53/2015 (2015-12-28)

### ISSUE THREAD

**Issue by USMortality** [akarlinsky/world_mortality#28]
The data for the USA and week 53/2015 of 2015-12-28 is missing! Any ideas why?

```R
world_deaths <- as_tibble(read.csv(
  "https://github.com/akarlinsky/world_mortality/raw/main/world_mortality.csv"
))
country_deaths <- world_deaths %>%
  filter(iso3c == "USA")
deaths <- country_deaths %>%
  mutate(date = paste0(
    year, "-", str_pad(time, 2, side = "left", "0"), "-1"
  )) %>%
  mutate(date = date_parse(date, format = "%G-%V-%u")) %>%
  tsibble(index = date)
scan_gaps(deaths)
```

```R
# A tsibble: 1 x 1 [7D]
  date      
  <date>    
1 2015-12-28
```

**Comment by akarlinsky** [comment]
Data in the US is from CDC ([Centers for Disease Control and Prevention](https://data.cdc.gov/api/views/y5bj-9g5w/rows.csv?accessType=DOWNLOAD)) and is by "epidemiological week". 

2015 has 52 such "epi-weeks". You can see a visualization of  this here:
https://gis.cdc.gov/grasp/fluview/mortality.html
![image](https://user-images.githubusercontent.com/48435065/200372747-6c565252-e28a-4773-970e-6736dfcbbd9d.png)

**Comment by USMortality** [comment]
Ok, so it's a parsing/date format issue, rather than a data problem. Thanks!
