### ISSUE TITLE
Local Mortality: India states

### ISSUE THREAD

**Issue by st2048** [akarlinsky/world_mortality#29]
Just wanted to share some data I've found from Indian states/UTs that I haven't seen in the most common repositories, in case this is of interest for local or preliminary mortality. Some official data for the whole of 2021 is starting to appear. Happy to share other data as I find it if you find it useful.

**Goa**

- Full monthly data from 2015 to 2021. Matches exactly with national CRS reports.
- Source: State [Annual Report for Births & Deaths](http://www.goadpse.gov.in/publications.htm)
- When compared to the SRS data for 2015-20, implied completeness is 132, 129, 138, 144, 152 and 159 per cent respectively. As Goa is a relatively small state, some of this difference might be because SRS is by place of residence whereas CRS is by place of death - however, as I am sure you know there are big states as well where the SRS underestimates mortality, so that could also be the reason here.
- Goa has a reputation of having a strong civil registration system and is the only state with 100% registration according to NFHS-5 (the survey in Goa was conducted in 2019 and asked about percentage of deaths from the past 3 years registered with the civil authority).
- Using 2015-19 trend as baseline would imply around 320-330 excess deaths per 100k.

State | Year | Month | Deaths
-- | -- | -- | --
Goa | 2015 | 1 | 1228
Goa | 2015 | 2 | 1065
Goa | 2015 | 3 | 1101
Goa | 2015 | 4 | 961
Goa | 2015 | 5 | 989
Goa | 2015 | 6 | 1020
Goa | 2015 | 7 | 1083
Goa | 2015 | 8 | 1062
Goa | 2015 | 9 | 1078
Goa | 2015 | 10 | 1112
Goa | 2015 | 11 | 1025
Goa | 2015 | 12 | 1014
Goa | 2016 | 1 | 863
Goa | 2016 | 2 | 1041
Goa | 2016 | 3 | 1017
Goa | 2016 | 4 | 996
Goa | 2016 | 5 | 1064
Goa | 2016 | 6 | 1110
Goa | 2016 | 7 | 1089
Goa | 2016 | 8 | 1286
Goa | 2016 | 9 | 1126
Goa | 2016 | 10 | 1084
Goa | 2016 | 11 | 1181
Goa | 2016 | 12 | 1273
Goa | 2017 | 1 | 1225
Goa | 2017 | 2 | 1072
Goa | 2017 | 3 | 1128
Goa | 2017 | 4 | 986
Goa | 2017 | 5 | 1028
Goa | 2017 | 6 | 948
Goa | 2017 | 7 | 1107
Goa | 2017 | 8 | 1099
Goa | 2017 | 9 | 1245
Goa | 2017 | 10 | 1049
Goa | 2017 | 11 | 1122
Goa | 2017 | 12 | 1011
Goa | 2018 | 1 | 1388
Goa | 2018 | 2 | 1067
Goa | 2018 | 3 | 1112
Goa | 2018 | 4 | 1111
Goa | 2018 | 5 | 1044
Goa | 2018 | 6 | 935
Goa | 2018 | 7 | 1100
Goa | 2018 | 8 | 1072
Goa | 2018 | 9 | 1072
Goa | 2018 | 10 | 1169
Goa | 2018 | 11 | 1076
Goa | 2018 | 12 | 926
Goa | 2019 | 1 | 1373
Goa | 2019 | 2 | 1129
Goa | 2019 | 3 | 1013
Goa | 2019 | 4 | 1098
Goa | 2019 | 5 | 1063
Goa | 2019 | 6 | 896
Goa | 2019 | 7 | 1149
Goa | 2019 | 8 | 1410
Goa | 2019 | 9 | 1170
Goa | 2019 | 10 | 1271
Goa | 2019 | 11 | 1084
Goa | 2019 | 12 | 1195
Goa | 2020 | 1 | 1259
Goa | 2020 | 2 | 1099
Goa | 2020 | 3 | 905
Goa | 2020 | 4 | 1056
Goa | 2020 | 5 | 1155
Goa | 2020 | 6 | 1006
Goa | 2020 | 7 | 1097
Goa | 2020 | 8 | 1217
Goa | 2020 | 9 | 1670
Goa | 2020 | 10 | 1538
Goa | 2020 | 11 | 1297
Goa | 2020 | 12 | 1302
Goa | 2021 | 1 | 1166
Goa | 2021 | 2 | 1121
Goa | 2021 | 3 | 1115
Goa | 2021 | 4 | 1428
Goa | 2021 | 5 | 3440
Goa | 2021 | 6 | 2320
Goa | 2021 | 7 | 1404
Goa | 2021 | 8 | 1317
Goa | 2021 | 9 | 1313
Goa | 2021 | 10 | 1354
Goa | 2021 | 11 | 1201
Goa | 2021 | 12 | 1158

**Delhi**

- Full monthly data from 2015 to 2021. Matches exactly with national CRS reports.
- Source: [Annual Report on Registration of Births and Deaths in Delhi](http://des.delhigovt.nic.in/wps/wcm/connect/DOIT_DES/des/our+services/publications/list+of+publications/vital+statistics+%28registration+of+births+and+deaths+in+delhi%29)
- When compared to the SRS data for 2015-20, implied completeness is 188, 188, 192, 225, 228 and 195 per cent respectively. In the case of Delhi, my understanding is that this difference is largely explained by non-residents who use the city hospitals.
- According to NFHS-5 registration completeness for Delhi residents was 89% (the survey in Delhi was mostly conducted in 2020 and asked about percentage of deaths from the past 3 years registered with the civil authority).
- When looking at the plotted monthly data, there does seem to be a drop from March 2020 onwards - whilst a 2015-19 trend baseline works well for the first couple of months in 2020, it does seem a bit too high after that, as it implies significantly below baseline mortality throughout 2020 and 2021 except for the months affected by covid waves. 
- Back when The Hindu had published [their story about Delhi](https://www.thehindu.com/news/cities/Delhi/excess-deaths-in-delhi-two-times-official-covid-19-toll/article36279423.ece) they had reported a drop in patients coming from other states in 2020, which could be the reason behind this drop - based on the plotted monthly data it does seem this trend continued throughout 2021. At the same time, I guess it's also possible that some people who died in Delhi hospitals during the covid peaks may have been residents from other states.
- The reports mention the data is by month of occurrence. The monthly patterns do match with the covid waves, and it is interesting to see how the 2021 peak in Delhi was in April as opposed to May, suggesting the wave hit Delhi earlier than some other parts of the country.

State | Year | Month | Deaths
-- | -- | -- | --
Delhi | 2015 | 1 | 12412
Delhi | 2015 | 2 | 11445
Delhi | 2015 | 3 | 10767
Delhi | 2015 | 4 | 9400
Delhi | 2015 | 5 | 10080
Delhi | 2015 | 6 | 8884
Delhi | 2015 | 7 | 9094
Delhi | 2015 | 8 | 10385
Delhi | 2015 | 9 | 11254
Delhi | 2015 | 10 | 10362
Delhi | 2015 | 11 | 9887
Delhi | 2015 | 12 | 10546
Delhi | 2016 | 1 | 13607
Delhi | 2016 | 2 | 11336
Delhi | 2016 | 3 | 10834
Delhi | 2016 | 4 | 10314
Delhi | 2016 | 5 | 11093
Delhi | 2016 | 6 | 9905
Delhi | 2016 | 7 | 11724
Delhi | 2016 | 8 | 12458
Delhi | 2016 | 9 | 14227
Delhi | 2016 | 10 | 12431
Delhi | 2016 | 11 | 11300
Delhi | 2016 | 12 | 12403
Delhi | 2017 | 1 | 12811
Delhi | 2017 | 2 | 10568
Delhi | 2017 | 3 | 11052
Delhi | 2017 | 4 | 10569
Delhi | 2017 | 5 | 11182
Delhi | 2017 | 6 | 10309
Delhi | 2017 | 7 | 10656
Delhi | 2017 | 8 | 11995
Delhi | 2017 | 9 | 10956
Delhi | 2017 | 10 | 12130
Delhi | 2017 | 11 | 11687
Delhi | 2017 | 12 | 12202
Delhi | 2018 | 1 | 15745
Delhi | 2018 | 2 | 12565
Delhi | 2018 | 3 | 12053
Delhi | 2018 | 4 | 11073
Delhi | 2018 | 5 | 11203
Delhi | 2018 | 6 | 11424
Delhi | 2018 | 7 | 10456
Delhi | 2018 | 8 | 11562
Delhi | 2018 | 9 | 12481
Delhi | 2018 | 10 | 12316
Delhi | 2018 | 11 | 11630
Delhi | 2018 | 12 | 13025
Delhi | 2019 | 1 | 15565
Delhi | 2019 | 2 | 12990
Delhi | 2019 | 3 | 12423
Delhi | 2019 | 4 | 10802
Delhi | 2019 | 5 | 11153
Delhi | 2019 | 6 | 11531
Delhi | 2019 | 7 | 10956
Delhi | 2019 | 8 | 11754
Delhi | 2019 | 9 | 11550
Delhi | 2019 | 10 | 11639
Delhi | 2019 | 11 | 11492
Delhi | 2019 | 12 | 13429
Delhi | 2020 | 1 | 14812
Delhi | 2020 | 2 | 13203
Delhi | 2020 | 3 | 11064
Delhi | 2020 | 4 | 8565
Delhi | 2020 | 5 | 11631
Delhi | 2020 | 6 | 15364
Delhi | 2020 | 7 | 10014
Delhi | 2020 | 8 | 9854
Delhi | 2020 | 9 | 10981
Delhi | 2020 | 10 | 10046
Delhi | 2020 | 11 | 13415
Delhi | 2020 | 12 | 13840
Delhi | 2021 | 1 | 12273
Delhi | 2021 | 2 | 10044
Delhi | 2021 | 3 | 10691
Delhi | 2021 | 4 | 35291
Delhi | 2021 | 5 | 27346
Delhi | 2021 | 6 | 9958
Delhi | 2021 | 7 | 9663
Delhi | 2021 | 8 | 11629
Delhi | 2021 | 9 | 10707
Delhi | 2021 | 10 | 11349
Delhi | 2021 | 11 | 10791
Delhi | 2021 | 12 | 11734

**Andhra Pradesh**

I'm not sure whether this is the same source as the one you have for your Andhra Pradesh data - I recently scrapped it again so I'm leaving here this more updated version in case it's useful.

- Monthly data from January 2018 to September 2022 - I excluded October and November 2022 because there may be significant revisions.
- Source: [Online Civil Registration Portal](https://crsorgi.gov.in/web/index.php/auth/MonitorReport/stCode/28) - I initially found this link [here](https://www.indiacovidmapping.org/reports/mortality/AndhraPradeshFactsheet.pdf). I am using 'registered deaths' column.
- This is online registration only, and represents 88% of all registered deaths in 2018, 90% in 2019 and 94% in 2020, when compared to the final numbers for the state in the CRS national reports.
- When compared to the SRS data for 2015-20, implied completeness (of the full CRS data, not just the online version) is 86, 90, 95, 108, 120 and 137 per cent respectively. Andhra Pradesh is a large state so I doubt that deaths of non-residents are a significant factor in these numbers, plus several other large states in South India have 100+ completeness according to the SRS, suggesting the SRS is underestimating mortality.
- The SRS suggests that the increase in deaths from 2019 to 2020 in Andhra Pradesh was completely explained by an increase in registration (it estimates 334,816 deaths for 2019 and 331,374 for 2020). The monthly data suggests this is implausible, as deaths only rise in the months were covid was prevalent and then fall back again. The data is by month of registration but I also recently analysed the column on 'registered within SLA (3 days)' and the monthly pattern is broadly similar, so the increase in late 2020 cannot be just late registrations.
- According to NFHS-5 registration completeness for Andhra Pradesh was 80.2% (the survey in Andhra Pradesh was conducted in 2019 and asked about percentage of deaths from the past 3 years registered with the civil authority). If I assume that two thirds of the deaths in NFHS-5 were from 2017 and 2018, with the remaining third from parts of 2016 and 2019, the equivalent SRS completeness estimate for that period would be 103%. This would suggest that if NFHS-5 figures are correct the SRS may be underestimating mortality by more than 20 percentage points in the state, though this is just a rough calculation.
- If we rescale SRS completeness data according to this estimate, we would get 67, 70, 75, 84, 94 and 107 per cent for 2015-20. This would suggest that the state may be getting close to completeness from 2019 onwards. I would be cautious with using SRS year on year changes though, as in the same way that the SRS seems to be wrong when it estimates that the rise from 2019 to 2020 is exclusively due to changes in completeness, it is possible that the SRS may also be wrong when it suggests that the rises in previous years were also mostly due to changes in completeness. I guess it is hard to know.
- Regardless of the specific baseline, it seems clear to me that there has been a big number of excess deaths in the state, and the peaks match the covid waves.

State | Year | Month | Deaths
-- | -- | -- | --
Andhra Pradesh | 2018 | 1 | 33457
Andhra Pradesh | 2018 | 2 | 28635
Andhra Pradesh | 2018 | 3 | 27174
Andhra Pradesh | 2018 | 4 | 25831
Andhra Pradesh | 2018 | 5 | 24226
Andhra Pradesh | 2018 | 6 | 26848
Andhra Pradesh | 2018 | 7 | 26293
Andhra Pradesh | 2018 | 8 | 27761
Andhra Pradesh | 2018 | 9 | 26483
Andhra Pradesh | 2018 | 10 | 28348
Andhra Pradesh | 2018 | 11 | 26645
Andhra Pradesh | 2018 | 12 | 29798
Andhra Pradesh | 2019 | 1 | 32149
Andhra Pradesh | 2019 | 2 | 31050
Andhra Pradesh | 2019 | 3 | 27865
Andhra Pradesh | 2019 | 4 | 26212
Andhra Pradesh | 2019 | 5 | 29813
Andhra Pradesh | 2019 | 6 | 30099
Andhra Pradesh | 2019 | 7 | 28360
Andhra Pradesh | 2019 | 8 | 28563
Andhra Pradesh | 2019 | 9 | 30341
Andhra Pradesh | 2019 | 10 | 33559
Andhra Pradesh | 2019 | 11 | 33095
Andhra Pradesh | 2019 | 12 | 31115
Andhra Pradesh | 2020 | 1 | 31890
Andhra Pradesh | 2020 | 2 | 26731
Andhra Pradesh | 2020 | 3 | 25332
Andhra Pradesh | 2020 | 4 | 22340
Andhra Pradesh | 2020 | 5 | 27987
Andhra Pradesh | 2020 | 6 | 28275
Andhra Pradesh | 2020 | 7 | 34583
Andhra Pradesh | 2020 | 8 | 54757
Andhra Pradesh | 2020 | 9 | 55556
Andhra Pradesh | 2020 | 10 | 41913
Andhra Pradesh | 2020 | 11 | 38472
Andhra Pradesh | 2020 | 12 | 39375
Andhra Pradesh | 2021 | 1 | 38170
Andhra Pradesh | 2021 | 2 | 32160
Andhra Pradesh | 2021 | 3 | 33868
Andhra Pradesh | 2021 | 4 | 39908
Andhra Pradesh | 2021 | 5 | 136548
Andhra Pradesh | 2021 | 6 | 67576
Andhra Pradesh | 2021 | 7 | 39491
Andhra Pradesh | 2021 | 8 | 35804
Andhra Pradesh | 2021 | 9 | 38772
Andhra Pradesh | 2021 | 10 | 35496
Andhra Pradesh | 2021 | 11 | 35414
Andhra Pradesh | 2021 | 12 | 37707
Andhra Pradesh | 2022 | 1 | 37729
Andhra Pradesh | 2022 | 2 | 37433
Andhra Pradesh | 2022 | 3 | 32102
Andhra Pradesh | 2022 | 4 | 28649
Andhra Pradesh | 2022 | 5 | 29898
Andhra Pradesh | 2022 | 6 | 32060
Andhra Pradesh | 2022 | 7 | 32122
Andhra Pradesh | 2022 | 8 | 35476
Andhra Pradesh | 2022 | 9 | 35204

**Comment by akarlinsky** [comment]
This is very helpful. The Delhi 2021 one is really fresh (I have been accessing that page every once in a while and last time I looked there was only 2020) and Goa I looked for but couldn't find.

Please send me an email at your earliest convenience. Address is on my personal website: https://akarlinsky.github.io/

**Comment by st2048** [comment]
> Please send me an email at your earliest convenience. Address is on my personal website: https://akarlinsky.github.io/

Thanks - just emailed you!

**Comment by dkobak** [comment]
@st2048 @akarlinsky Can this issue be closed now?
