### ISSUE TITLE
Switch to STMF for Sweden?

### ISSUE THREAD

**Issue by Nettsentrisk** [akarlinsky/world_mortality#32]
The Swedish data series is stranded in mid-April 2023, due to lack of updates from Swedish authorities at the source provided. Yet in the STMF data, the Swedish data is updated as per week 34.

Any reason why Sweden is not among the countries where STMF data are being used, especially when the current source has not updated for a such a long time?

**Comment by akarlinsky** [comment]
Thanks, we will look into this. 
Several countries have changed their reporting strategies by now so there may be other changes we could do.

Keeping this open until we decide what to do.

**Comment by akarlinsky** [comment]
We have updated Sweden's data for 2023 using the weekly data from EuroStat and deaths by known month up to August 2023 and will keep this updated.

See the README note for Sweden's data and method 2023. 
You can close this issue if you think this is ok.
