### ISSUE TITLE
Nicaragua 2020 data

### ISSUE THREAD

**Issue by akarlinsky** [akarlinsky/world_mortality#5]
We currently do not have 2019 data for Nicaragua and our 2020 data mixes some estimates with official cumulative data. 

If anyone has a source for 2019 data and/or 2020 raw data used by Carlos Hernández to derive his estimates, please contribute it to us.

**Comment by akarlinsky** [comment]
2019 monthly data was added on commit 387c3d353f530854b77cf410334edd22660ac56a.

**Comment by dkobak** [comment]
Complete 2020 data have been added! Closing.
