### ISSUE TITLE
Tunisia mortality data missing for week 53 of 2020

### ISSUE THREAD

**Issue by czka** [akarlinsky/world_mortality#7]
A follow-up of https://github.com/owid/covid-19-data/issues/872, where @akarlinsky wrote:

> The data for Tunisia is digitized from a figure on their NSO's report.
> This is (most likely) NOT ISO weeks, so there will be no week 53 for 2015 or 2020.
> 
> We are keeping track of the monthly figures for Tunisia as well (they are much more delayed than the report), and might correct for iso weeks using it, but for now this is the best we have.

**Comment by dkobak** [comment]
@akarlinsky Should we close it because we switched to monthly?

**Comment by czka** [comment]
FWIW - OK with me. My charts for Tunisia (https://github.com/czka/covid_toll_tool/blob/main/covid_toll_ALL/Tunisia_2020.png, https://github.com/czka/covid_toll_tool/blob/main/covid_toll_ALL/Tunisia_2021.png) are fine at monthly interval as well.

**Comment by akarlinsky** [comment]
Tunisia data changed to monthly in commit https://github.com/akarlinsky/world_mortality/commit/f5be8608e9a4f8fbe157590f11f7b209a8254de7 so issue is no longer relevant.
