### ISSUE TITLE
South Africa year=0, for period before 2020 and 2021 

### ISSUE THREAD

**Issue by Rob1to** [akarlinsky/world_mortality#8]
South Africa year equals  zero,  just before 2020 and 2021 values.  

There is uncertainty whether this value 0 corresponds to 2019 or to another year before 2019.

Thanks for collecting and making available excess death data.

**Comment by dkobak** [comment]
See README:

> SAMRC does not publish weekly data for years before 2020. Instead, the 2018--2019 data were used by SAMRC to forecast expected weekly mortality using the Excel Holt-Winters time series forecasting method in Excel function. We denote this forecast as year = 0 in the data.
