### ISSUE TITLE
STMF/Eurostat harmonizing

### ISSUE THREAD

**Issue by dkobak** [akarlinsky/world_mortality#9]
Regarding this:

> For some European countries, STMF sometimes has more up-to-date (and backward revised) data than Eurostat, as it culls data from countries' NSOs. For each data point that exists in both datasets, we take the maximum between them as the final data.

Is this still accurate? I still think we should change it. How about we default to STMF unless Eurostat has more recent weeks available in which case you append additional weeks from Eurostat to the STMF data?

**Comment by akarlinsky** [comment]
Fixed in f19ebf4ae856c1bcd344fc51c05db52ac11bb2cc.
